openapi: 3.0.3
info:
    title: Knowtfolio Backend
    description: Blogging platform that leverages NFT to grow, buy and sell articles.
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /api/articles:
        post:
            tags:
                - articles
            summary: Create articles
            description: Create new article.
            operationId: articles#Create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
                            title: My Awesome Title
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody2'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Title
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - cognito_id_token_header_Authorization: []
    /api/articles/{id}:
        delete:
            tags:
                - articles
            summary: Delete articles
            description: Delete article by id.
            operationId: articles#Delete
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteResponseBodyOnlyID2'
                            example:
                                id: exampleId01
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - cognito_id_token_header_Authorization: []
        get:
            tags:
                - articles
            summary: Read articles
            description: Get article by id.
            operationId: articles#Read
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ReadResponseBodyWithOwnerInfo'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                                owner_id: exampleId01
                                title: My Awesome Title
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - articles
            summary: Update articles
            description: Update an article.
            operationId: articles#Update
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
                            title: My Awesome Title
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody2'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Title
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
            security:
                - cognito_id_token_header_Authorization: []
    /api/health:
        get:
            tags:
                - healthcheck
            summary: Get health status. healthcheck
            description: Check server health.
            operationId: healthcheck#Get health status.
            responses:
                "200":
                    description: サービスが正常に機能している場合
                "500":
                    description: 'database_unhealthy: サーバは生きているが、DBと接続できない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "503":
                    description: 'contract_unhealthy: サーバは生きているが、ブロックチェーン上のスマートコントラクトと接続できない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/nfts/{article_id}:
        post:
            tags:
                - nfts
            summary: Create for Article nfts
            description: MINT an NFT of the article.
            operationId: nfts#Create for Article
            parameters:
                - name: article_id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateForArticleRequestBody'
                        example:
                            address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                            signature: Ipsam veritatis praesentium repellendus est esse assumenda.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateNftForArticleResult'
                            example:
                                cost: 829421888521491104
                                hash: Veritatis et.
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/questions:
        post:
            tags:
                - questions
            summary: Create questions
            description: Create new question.
            operationId: questions#Create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
                            title: My Awesome Title
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Title
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/questions/{id}:
        delete:
            tags:
                - questions
            summary: Delete questions
            description: Delete question by id.
            operationId: questions#Delete
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteResponseBodyOnlyID'
                            example:
                                id: exampleId01
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - questions
            summary: Read questions
            description: Get question by id.
            operationId: questions#Read
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Title
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - questions
            summary: Update questions
            description: Update question by id.
            operationId: questions#Update
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
                            title: My Awesome Title
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Title
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/questions/{id}/answers:
        post:
            tags:
                - questions
            summary: Create Answer questions
            description: Create an answer for a question.
            operationId: questions#Create Answer
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateAnswerRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateAnswerResponseBody'
                            example:
                                answer_id: exampleId01
                                content: <h1> Hello World! </h1>
                                question_id: exampleId01
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/questions/{id}/answers/{answer_id}:
        delete:
            tags:
                - questions
            summary: Delete Answer questions
            description: Delete an answer for a question.
            operationId: questions#Delete Answer
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
                - name: answer_id
                  in: path
                  description: 回答のID
                  required: true
                  schema:
                    type: string
                    description: 回答のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteAnswerResponseBodyOnlyID'
                            example:
                                answer_id: exampleId01
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - questions
            summary: Read Answer questions
            description: Read an answer for a question.
            operationId: questions#Read Answer
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
                - name: answer_id
                  in: path
                  description: 回答のID
                  required: true
                  schema:
                    type: string
                    description: 回答のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateAnswerResponseBody'
                            example:
                                answer_id: exampleId01
                                content: <h1> Hello World! </h1>
                                question_id: exampleId01
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - questions
            summary: Update Answer questions
            description: Update an answer for a question.
            operationId: questions#Update Answer
            parameters:
                - name: id
                  in: path
                  description: 質問のID
                  required: true
                  schema:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
                - name: answer_id
                  in: path
                  description: 回答のID
                  required: true
                  schema:
                    type: string
                    description: 回答のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateAnswerRequestBody'
                        example:
                            content: <h1> Hello World! </h1>
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateAnswerResponseBody'
                            example:
                                answer_id: exampleId01
                                content: <h1> Hello World! </h1>
                                question_id: exampleId01
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/search:
        get:
            tags:
                - search
            summary: Search for Articles search
            description: Get articles that matches to the request query.
            operationId: search#Search for Articles
            parameters:
                - name: keywords
                  in: query
                  description: 検索に使用するキーワード。`+`で区切ることで、複数指定可能
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: 検索に使用するキーワード。`+`で区切ることで、複数指定可能
                    example: Golang+NFT
                  example: Golang+NFT
                - name: owned_by
                  in: query
                  description: 記事の所有者のUserID。指定がない場合、全ての所有者の記事を検索する。
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: 記事の所有者のUserID。指定がない場合、全ての所有者の記事を検索する。
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 1
                    maxLength: 40
                  example: exampleId01
                - name: sort_by
                  in: query
                  description: 記事をソートするkey
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: 記事をソートするkey
                    default: created_at
                    example: updated_at
                    enum:
                        - created_at
                        - updated_at
                  example: updated_at
                - name: page_num
                  in: query
                  description: 取得したい位置のページ番号（1-indexed）
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: 取得したい位置のページ番号（1-indexed）
                    default: 1
                    example: 5023432583872562117
                    minimum: 1
                  example: 9266367122726675364
                - name: page_size
                  in: query
                  description: 1ページあたりのコンテンツ数
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: 1ページあたりのコンテンツ数
                    default: 10
                    example: 40
                    minimum: 1
                    maximum: 100
                  example: 69
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Searchresult'
                            example:
                                results:
                                    - id: exampleId01
                                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                                      owner_id: exampleId01
                                      title: My Awesome Title
                                    - id: exampleId01
                                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                                      owner_id: exampleId01
                                      title: My Awesome Title
                                    - id: exampleId01
                                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                                      owner_id: exampleId01
                                      title: My Awesome Title
                                total_count: 18225424149782934695
    /articles/{id}:
        get:
            tags:
                - articles-html
            summary: Read HTML articles-html
            description: Get article's HTML by id.
            operationId: articles-html#Read HTML
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: IDに対応する記事のHTMLのバイナリ
                    content:
                        text/html; charset=UTF-8:
                            schema:
                                type: string
                                example: <h1> Hello World! </h1>
                                format: binary
                            example: <h1> Hello World! </h1>
                "404":
                    description: 'not_found: IDに対応するリソースが見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateAnswerRequestBody:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
            example:
                content: <h1> Hello World! </h1>
            required:
                - content
        CreateAnswerResponseBody:
            type: object
            properties:
                answer_id:
                    type: string
                    description: 回答のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                question_id:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
            description: Create AnswerResponseBody result type (default view)
            example:
                answer_id: exampleId01
                content: <h1> Hello World! </h1>
                question_id: exampleId01
            required:
                - answer_id
                - question_id
                - content
        CreateForArticleRequestBody:
            type: object
            properties:
                address:
                    type: string
                    description: ウォレットのアドレス
                    example: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                    pattern: ^0x[a-fA-F0-9]{40}$
                signature:
                    type: string
                    description: '`address`のアカウントが行った署名'
                    example: Distinctio consectetur doloremque.
            example:
                address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                signature: Dolor sapiente laboriosam veniam eos eos.
            required:
                - address
                - signature
        CreateNftForArticleResult:
            type: object
            properties:
                cost:
                    type: integer
                    description: トークン発行にかかったコスト
                    example: 4471315468130594924
                    format: int64
                hash:
                    type: string
                    description: トランザクションのハッシュ
                    example: Et esse molestiae illum temporibus mollitia voluptatem.
            example:
                cost: 5255393866423437156
                hash: Nesciunt alias nulla fuga nihil.
            required:
                - hash
                - cost
        CreateRequestBody:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                title:
                    type: string
                    example: My Awesome Title
            description: 作成したい質問の情報
            example:
                content: <h1> Hello World! </h1>
                title: My Awesome Title
            required:
                - title
                - content
        CreateResponseBody:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                id:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                title:
                    type: string
                    example: My Awesome Title
            description: CreateResponseBody result type (default view)
            example:
                content: <h1> Hello World! </h1>
                id: exampleId01
                title: My Awesome Title
            required:
                - id
                - title
                - content
        CreateResponseBody2:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                title:
                    type: string
                    example: My Awesome Title
            description: CreateResponseBody result type (default view)
            example:
                content: <h1> Hello World! </h1>
                id: exampleId01
                title: My Awesome Title
            required:
                - id
                - title
                - content
        DeleteAnswerResponseBodyOnlyID:
            type: object
            properties:
                answer_id:
                    type: string
                    description: 回答のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
            description: Delete AnswerResponseBody result type (only-id view)
            example:
                answer_id: exampleId01
            required:
                - answer_id
        DeleteResponseBodyOnlyID:
            type: object
            properties:
                id:
                    type: string
                    description: 質問のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
            description: DeleteResponseBody result type (only-id view)
            example:
                id: exampleId01
            required:
                - id
        DeleteResponseBodyOnlyID2:
            type: object
            properties:
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
            description: DeleteResponseBody result type (only-id view)
            example:
                id: exampleId01
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        ReadResponseBodyWithOwnerInfo:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                owner_address:
                    type: string
                    description: 所有者のウォレットのアドレス
                    example: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                    pattern: ^0x[a-fA-F0-9]{40}$
                owner_id:
                    type: string
                    description: 所有者のUserID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 1
                    maxLength: 40
                title:
                    type: string
                    example: My Awesome Title
            description: ReadResponseBody result type (with-owner-info view)
            example:
                content: <h1> Hello World! </h1>
                id: exampleId01
                owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                owner_id: exampleId01
                title: My Awesome Title
            required:
                - id
                - title
                - content
                - owner_id
        SearchResultEntry:
            type: object
            properties:
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                owner_address:
                    type: string
                    description: 所有者のウォレットのアドレス
                    example: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                    pattern: ^0x[a-fA-F0-9]{40}$
                owner_id:
                    type: string
                    description: 所有者のUserID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 1
                    maxLength: 40
                title:
                    type: string
                    example: My Awesome Title
            example:
                id: exampleId01
                owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                owner_id: exampleId01
                title: My Awesome Title
            required:
                - id
                - title
                - owner_id
        Searchresult:
            type: object
            properties:
                results:
                    type: array
                    items:
                        $ref: '#/components/schemas/SearchResultEntry'
                    description: 指定したページ内の検索結果
                    example:
                        - id: exampleId01
                          owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                          owner_id: exampleId01
                          title: My Awesome Title
                        - id: exampleId01
                          owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                          owner_id: exampleId01
                          title: My Awesome Title
                        - id: exampleId01
                          owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                          owner_id: exampleId01
                          title: My Awesome Title
                total_count:
                    type: integer
                    description: 指定したページを含めたすべての検索結果の件数
                    example: 5613503003369806042
            example:
                results:
                    - id: exampleId01
                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                      owner_id: exampleId01
                      title: My Awesome Title
                    - id: exampleId01
                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                      owner_id: exampleId01
                      title: My Awesome Title
                    - id: exampleId01
                      owner_address: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 '
                      owner_id: exampleId01
                      title: My Awesome Title
                total_count: 12784667946624386665
            required:
                - results
                - total_count
        UpdateRequestBody:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                title:
                    type: string
                    example: My Awesome Title
            description: |-
                質問の更新内容
                リクエストに含まれるフィールドだけ更新される。
            example:
                content: <h1> Hello World! </h1>
                title: My Awesome Title
    securitySchemes:
        cognito_id_token_header_Authorization:
            type: http
            description: Cognitoで生成されたIDトークンのJWT
            scheme: bearer
tags:
    - name: articles-html
      description: SEO対策で、記事の表示だけ直接HTMLで返すためのサービス
    - name: healthcheck
      description: 疎通確認サービス
    - name: nfts
      description: NFTを管理するサービス
    - name: questions
      description: 質問サービス
    - name: search
      description: 検索サービス
    - name: articles
      description: 記事サービス
